format:
	cargo fmt --quiet

test:
	cargo test --quiet

run:
	cargo run --quiet

build:
	cargo build --quiet

lint:
	cargo clippy --quiet

clean:
	cargo clean

.PHONY: format test run build lint clean

all: format test run build lint